export const ADMIN_NAV = [
  { href: "/admin", label: "Home", group: "primary" },
  { href: "/admin/chats", label: "Inbox", group: "primary" },
  { href: "/admin/leads", label: "Leads" },
  { href: "/admin/pipeline", label: "Pipeline" },
  { href: "/admin/analytics", label: "Revenue", group: "primary" },
  { href: "/admin/automation", label: "Automation", group: "secondary" },
  { href: "/admin/payments", label: "Payments", group: "secondary" },
  { href: "/admin/team", label: "Team", group: "secondary" },
  { href: "/admin/partners", label: "Partners", group: "secondary" },
  { href: "/admin/branding", label: "Branding", group: "secondary" },
  { href: "/admin/my-ai", label: "AI Workspace", group: "secondary" },
  { href: "/admin/ai-control", label: "AI Control Center", group: "secondary" },
  { href: "/admin/settings", label: "Settings", group: "secondary" },
];
