export const ADMIN_NAV = [
  { href: "/admin", label: "Dashboard" },
  { href: "/admin/chats", label: "Inbox" },
  { href: "/admin/leads", label: "Leads" },
  { href: "/admin/pipeline", label: "Pipeline" },
  { href: "/admin/analytics", label: "Analytics" },
  { href: "/admin/automation", label: "Automation" },
  { href: "/admin/payments", label: "Payments" },
  { href: "/admin/team", label: "Team" },
  { href: "/admin/partners", label: "Partners" },
  { href: "/admin/branding", label: "Branding" },
  { href: "/admin/my-ai", label: "My AI Workspace" },
  { href: "/admin/ai-control", label: "AI Control Center" },
  { href: "/admin/settings", label: "Settings" },
];
